name: Parity Check
on: [push, pull_request]
jobs:
  parity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          pip install -r common/requirements.txt
      - name: Scan
        run: |
          python common/parity_scan.py $(git ls-files '*.cif') 